export const SEDENTARY = 'SEDENTARY'
export const LIGHT_EXERCISE = 'LIGHT_EXERCISE'
export const DAILY_EXERCISE = 'DAILY_EXERCISE'
export const INTENSE_EXERCISE = 'INTENSE_EXERCISE'
export const EXTREME_EXERCISE = 'EXTREME_EXERCISE'

export type SEDENTARY = 'SEDENTARY'
export type LIGHT_EXERCISE = 'LIGHT_EXERCISE'
export type DAILY_EXERCISE = 'DAILY_EXERCISE'
export type INTENSE_EXERCISE = 'INTENSE_EXERCISE'
export type EXTREME_EXERCISE = 'EXTREME_EXERCISE'

export type EXERCISE_ACTIVITY_TYPE =
    | SEDENTARY
    | LIGHT_EXERCISE
    | DAILY_EXERCISE
    | INTENSE_EXERCISE
    | EXTREME_EXERCISE
    | undefined

export const EXTREME_WEIGHT_GAIN = 'EXTREME_WEIGHT_GAIN'
export const WEIGHT_GAIN = 'WEIGHT_GAIN'
export const MILD_WEIGHT_GAIN = 'MILD_WEIGHT_GAIN'
export const MAINTAIN_WEIGHT = 'MAINTAIN_WEIGHT'
export const MILD_WEIGHT_LOSS = 'MILD_WEIGHT_LOSS'
export const WEIGHT_LOSS = 'WEIGHT_LOSS'
export const EXTREME_WEIGHT_LOSS = 'EXTREME_WEIGHT_LOSS'

export type EXTREME_WEIGHT_GAIN = 'EXTREME_WEIGHT_GAIN'
export type WEIGHT_GAIN = 'WEIGHT_GAIN'
export type MILD_WEIGHT_GAIN = 'MILD_WEIGHT_GAIN'
export type MAINTAIN_WEIGHT = 'MAINTAIN_WEIGHT'
export type MILD_WEIGHT_LOSS = 'MILD_WEIGHT_LOSS'
export type WEIGHT_LOSS = 'WEIGHT_LOSS'
export type EXTREME_WEIGHT_LOSS = 'EXTREME_WEIGHT_LOSS'
