export const colors = {
	mainColor: "#b2dbfa",
	secondColor: "#6EB9FB",
	highlight: "#41D975",
	error: "#cc0000",
	black: "#141421",
	black75: "#141421BF",
	black50: "#14142180",
	black25: "#14142140",
	black10: "#1414211A",
	white: "#f3f4f5",
	white75: "#f3f4f5BF",
	white50: "#f3f4f580",
	white25: "#f3f4f540",
	white10: "#f3f4f51A",
};

export default {
	light: {
		primary: colors.mainColor,
		text: colors.black,
		link: colors.secondColor,
		highlight: colors.highlight,
		error: colors.error,
		placeholder: colors.black50,
		background: colors.white,
		button: colors.mainColor,
		tint: colors.mainColor,
		tabIconDefault: colors.black,
		tabIconSelected: colors.mainColor,
	},
	dark: {
		primary: colors.mainColor,
		text: colors.white,
		link: colors.mainColor,
		highlight: colors.secondColor,
		error: colors.error,
		placeholder: colors.white50,
		background: colors.black,
		button: colors.mainColor,
		tint: colors.mainColor,
		tabIconDefault: colors.black,
		tabIconSelected: colors.mainColor,
	},
};
