// ! AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'

export const OFFLINE = 'OFFLINE'

// ! FOOD SEARCH TYPES
export const FOOD_SEARCH_SUCCESS = 'FOOD_SEARCH_SUCCESS'
export const FOOD_SEARCH_FAIL = 'FOOD_SEARCH_FAIL'
export const FOOD_SUCCESS = 'FOOD_SUCCESS'
// ! SPORT SEARCH TYPES
export const SPORT_SEARCH_SUCCESS = 'SPORT_SEARCH_SUCCESS'
export const SPORT_SEARCH_FAIL = 'SPORT_SEARCH_FAIL'
export const SPORT_SUCCESS = 'SPORT_SUCCESS'
// ! DIET TYPES
export const DIET_UPDATE_MAX = 'DIET_UPDATE_MAX'
export const DIET_UPDATE = 'DIET_UPDATE'
export const DIET_DEFAULT = 'DIET_DEFAULT'
