// ! AUTH TYPES
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

// ! FOOD TYPES
export const FOOD_SEARCH_SUCCESS = 'FOOD_SEARCH_SUCCESS'
export const FOOD_SEARCH_FAIL = 'FOOD_SEARCH_FAIL'
